-- CreateEnum
CREATE TYPE "LLMModels" AS ENUM ('GPT35TURBO', 'GPT4TURBO', 'LLAMA3', 'CLAUDEOPUS', 'GPT4O');

-- AlterTable
ALTER TABLE "Prompt" ADD COLUMN     "model" "LLMModels" NOT NULL DEFAULT 'GPT35TURBO';
