export enum MODELS {
  Workspace = 'Workspace',
  Team = 'Team',
  Label = 'Label',
  UsersOnWorkspaces = 'UsersOnWorkspaces',
  View = 'View',
  Action = 'Action',

  // Team
  Workflow = 'Workflow',
  Issue = 'Issue',
  IssueHistory = 'IssueHistory',
  IssueComment = 'IssueComment',
  IntegrationDefinition = 'IntegrationDefinition',
  IntegrationAccount = 'IntegrationAccount',
  LinkedIssue = 'LinkedIssue',
  IssueRelation = 'IssueRelation',
  Notification = 'Notification',
  IssueSuggestion = 'IssueSuggestion',
  Project = 'Project',
  ProjectMilestone = 'ProjectMilestone',
  Cycle = 'Cycle',
  Conversation = 'Conversation',
  ConversationHistory = 'ConversationHistory',
}
